
import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author Thiago Moura
 */
public class Tela extends javax.swing.JFrame {
    private JLabel[][] casas;
    private Tabuleiro tab;
    private ArrayList<JMenuItem> itens;
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        inicializar();
        visualizarPainel(painelFilhoIniciar.getName());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPai = new javax.swing.JLayeredPane();
        painelFilhoIniciar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPequeno = new javax.swing.JButton();
        btnMedio = new javax.swing.JButton();
        btnGrande = new javax.swing.JButton();
        painelFilhoTabuleiro = new javax.swing.JPanel();
        barraMenus = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        itemInicio = new javax.swing.JMenuItem();
        menuDebug = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selcione o tamanho do Ambiente:");

        btnPequeno.setText("Pequeno");
        btnPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPequenoActionPerformed(evt);
            }
        });

        btnMedio.setText("Médio");
        btnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioActionPerformed(evt);
            }
        });

        btnGrande.setText("Grande");
        btnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrandeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFilhoIniciarLayout = new javax.swing.GroupLayout(painelFilhoIniciar);
        painelFilhoIniciar.setLayout(painelFilhoIniciarLayout);
        painelFilhoIniciarLayout.setHorizontalGroup(
            painelFilhoIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFilhoIniciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelFilhoIniciarLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(painelFilhoIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPequeno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelFilhoIniciarLayout.setVerticalGroup(
            painelFilhoIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFilhoIniciarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPequeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrande)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        painelFilhoTabuleiro.setLayout(new java.awt.GridLayout(6, 6));

        javax.swing.GroupLayout painelPaiLayout = new javax.swing.GroupLayout(painelPai);
        painelPai.setLayout(painelPaiLayout);
        painelPaiLayout.setHorizontalGroup(
            painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFilhoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelFilhoTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPaiLayout.setVerticalGroup(
            painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFilhoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelFilhoTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPai.setLayer(painelFilhoIniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        painelFilhoIniciar.getAccessibleContext().setAccessibleName("Iniciar");
        painelPai.setLayer(painelFilhoTabuleiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelFilhoTabuleiro.getAccessibleContext().setAccessibleName("Tabuleiro");
        painelFilhoTabuleiro.getAccessibleContext().setAccessibleDescription("");

        menuPrincipal.setText("Menu");

        itemInicio.setText("Inicio");
        itemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInicioActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemInicio);

        barraMenus.add(menuPrincipal);

        menuDebug.setText("Debug");
        barraMenus.add(menuDebug);

        setJMenuBar(barraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPequenoActionPerformed
        iniciarTabuleiro(6,6,2,2);
    }//GEN-LAST:event_btnPequenoActionPerformed

    private void itemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInicioActionPerformed
        visualizarPainel(this.painelFilhoIniciar.getName());
    }//GEN-LAST:event_itemInicioActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioActionPerformed
        iniciarTabuleiro(15,20,4,6);
    }//GEN-LAST:event_btnMedioActionPerformed

    private void btnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrandeActionPerformed
        iniciarTabuleiro(30,45,8,10);
    }//GEN-LAST:event_btnGrandeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JButton btnGrande;
    private javax.swing.JButton btnMedio;
    private javax.swing.JButton btnPequeno;
    private javax.swing.JMenuItem itemInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuDebug;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JPanel painelFilhoIniciar;
    private javax.swing.JPanel painelFilhoTabuleiro;
    private javax.swing.JLayeredPane painelPai;
    // End of variables declaration//GEN-END:variables

    private void inicializar(){
        painelFilhoIniciar.setName("Iniciar");
        painelFilhoTabuleiro.setName("Tabuleiro");
    }
    
    private void visualizarPainel(String nome){
        painelFilhoIniciar.setVisible(painelFilhoIniciar.getName().equalsIgnoreCase(nome));
        painelFilhoTabuleiro.setVisible(painelFilhoTabuleiro.getName().equalsIgnoreCase(nome));
    }
    private void iniciarTabuleiro(int dimenssao,int lixos,int lixeiras,int agentes){
        painelFilhoTabuleiro.removeAll();
        painelFilhoTabuleiro.setSize(dimenssao*50, dimenssao*50);
        painelFilhoTabuleiro.setLayout(new java.awt.GridLayout(dimenssao, dimenssao));
        
        this.tab = new Tabuleiro(dimenssao);
        this.casas = new JLabel[dimenssao][dimenssao];
        
        tab.posicionarLixos(lixos);
        tab.posicionarLixeiras(lixeiras, lixos/lixeiras);
        
        atualizarTabuleiro();
        
        visualizarPainel(painelFilhoTabuleiro.getName());
    }
    private void atualizarTabuleiro(){
        int d = tab.getDimenssao();
        for(int l=0;l<d;l++){
            for(int c=0;c<d;c++){
                JLabel jl = new JLabel();Border eb = new LineBorder(Color.BLACK);
                jl.setBorder(eb);
                jl.setHorizontalAlignment(JLabel.CENTER);
                
                Casa cs = tab.getCasa(l, c);
                if(cs.casaVazia())jl.setText("");
                else jl.setText(cs.getPeca().getNome());
                
                casas[l][c] = jl;
                painelFilhoTabuleiro.add(casas[l][c]);
            }
        }
    }
    //Funções Debug para testes (Não implementado)
    private void CriarItensMenuDebug(){
        itens = new ArrayList<>();
        Iterator it = tab.getLixeiras().iterator();
        while(it.hasNext()){
            Lixeira lx = (Lixeira) it.next();
            itens.add(new JMenuItem(lx.getNome()));
        }
        
    }
    private void CriarMenuDebug(){
        CriarItensMenuDebug();
        Iterator it = itens.iterator();
        menuDebug.removeAll();
        while(it.hasNext()){
            menuDebug.add((JMenuItem) it.next());
        }
    }
}
