
import com.sun.javafx.css.Style;
import java.awt.Color;
import java.awt.Dimension;
import java.util.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author Thiago Moura
 */
public class Tela extends javax.swing.JFrame implements SaidaSimulador{
    private JLabel[][] quadrantes;
    private ArrayList<JMenuItem> itens;
    private Simulador simulador;
    private boolean ambienteIniciado;
    private int dimenssao;
    private int qtdLixos;
    private int qtdLixeiras;
    private int qtdAgentes;
    /**
     * Creates new form Tela
     */
    public Tela(){
        initComponents();
        inicializaBotoes();
        this.setLocationRelativeTo(null);
        selPequenoActionPerformed(null);
        this.ambienteIniciado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gupoTamanho = new javax.swing.ButtonGroup();
        painelPai = new javax.swing.JPanel();
        painelBarra = new javax.swing.JPanel();
        barra = new javax.swing.JToolBar();
        selPequeno = new javax.swing.JToggleButton();
        selMedio = new javax.swing.JToggleButton();
        selGrande = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        selIniciar = new javax.swing.JToggleButton();
        btnProximoCiclo = new javax.swing.JButton();
        btnProximoAgente = new javax.swing.JButton();
        painelFilhoAmbiente = new javax.swing.JPanel();
        scrollAmbiente = new javax.swing.JScrollPane();
        painelScrollAmbiente = new javax.swing.JPanel();
        painelAmbiente = new javax.swing.JPanel();
        painelInformacoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoInformacoes = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agentes Recicladores");

        painelPai.setLayout(new java.awt.BorderLayout(5, 0));

        barra.setFloatable(false);
        barra.setRollover(true);

        gupoTamanho.add(selPequeno);
        selPequeno.setSelected(true);
        selPequeno.setText("Pequeno");
        selPequeno.setFocusable(false);
        selPequeno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selPequeno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPequenoActionPerformed(evt);
            }
        });
        barra.add(selPequeno);

        gupoTamanho.add(selMedio);
        selMedio.setText("Médio");
        selMedio.setFocusable(false);
        selMedio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selMedio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selMedioActionPerformed(evt);
            }
        });
        barra.add(selMedio);

        gupoTamanho.add(selGrande);
        selGrande.setText("Grande");
        selGrande.setFocusable(false);
        selGrande.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selGrande.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selGrandeActionPerformed(evt);
            }
        });
        barra.add(selGrande);
        barra.add(jSeparator1);

        selIniciar.setText("Iniciar");
        selIniciar.setFocusable(false);
        selIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selIniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selIniciarActionPerformed(evt);
            }
        });
        barra.add(selIniciar);

        btnProximoCiclo.setText("Próximo Ciclo");
        btnProximoCiclo.setFocusable(false);
        btnProximoCiclo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximoCiclo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProximoCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoCicloActionPerformed(evt);
            }
        });
        barra.add(btnProximoCiclo);

        btnProximoAgente.setText("Próximo Agente");
        btnProximoAgente.setFocusable(false);
        btnProximoAgente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximoAgente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProximoAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoAgenteActionPerformed(evt);
            }
        });
        barra.add(btnProximoAgente);

        javax.swing.GroupLayout painelBarraLayout = new javax.swing.GroupLayout(painelBarra);
        painelBarra.setLayout(painelBarraLayout);
        painelBarraLayout.setHorizontalGroup(
            painelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        painelBarraLayout.setVerticalGroup(
            painelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        painelPai.add(painelBarra, java.awt.BorderLayout.PAGE_START);

        painelAmbiente.setBackground(new java.awt.Color(255, 255, 255));
        painelAmbiente.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout painelScrollAmbienteLayout = new javax.swing.GroupLayout(painelScrollAmbiente);
        painelScrollAmbiente.setLayout(painelScrollAmbienteLayout);
        painelScrollAmbienteLayout.setHorizontalGroup(
            painelScrollAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelScrollAmbienteLayout.setVerticalGroup(
            painelScrollAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        scrollAmbiente.setViewportView(painelScrollAmbiente);

        javax.swing.GroupLayout painelFilhoAmbienteLayout = new javax.swing.GroupLayout(painelFilhoAmbiente);
        painelFilhoAmbiente.setLayout(painelFilhoAmbienteLayout);
        painelFilhoAmbienteLayout.setHorizontalGroup(
            painelFilhoAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        painelFilhoAmbienteLayout.setVerticalGroup(
            painelFilhoAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollAmbiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        painelPai.add(painelFilhoAmbiente, java.awt.BorderLayout.CENTER);
        painelFilhoAmbiente.getAccessibleContext().setAccessibleName("Tabuleiro");
        painelFilhoAmbiente.getAccessibleContext().setAccessibleDescription("");

        painelInformacoes.setPreferredSize(new java.awt.Dimension(250, 429));

        campoInformacoes.setEditable(false);
        campoInformacoes.setBackground(new java.awt.Color(255, 255, 204));
        campoInformacoes.setContentType("text/html"); // NOI18N
        campoInformacoes.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n\n    </p>\r\n  </body>\r\n</html>\r\n");
        campoInformacoes.setToolTipText("");
        jScrollPane1.setViewportView(campoInformacoes);

        javax.swing.GroupLayout painelInformacoesLayout = new javax.swing.GroupLayout(painelInformacoes);
        painelInformacoes.setLayout(painelInformacoesLayout);
        painelInformacoesLayout.setHorizontalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        painelInformacoesLayout.setVerticalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        painelPai.add(painelInformacoes, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPequenoActionPerformed
        this.qtdLixos = 6;
        this.qtdLixeiras = 2;
        this.qtdAgentes = 2;
        this.dimenssao = 6;
        criarAmbiente();
    }//GEN-LAST:event_selPequenoActionPerformed

    private void selMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selMedioActionPerformed
        this.qtdLixos = 20;
        this.qtdLixeiras = 4;
        this.qtdAgentes = 6;
        this.dimenssao = 15;
        criarAmbiente();
    }//GEN-LAST:event_selMedioActionPerformed

    private void selGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selGrandeActionPerformed
        this.qtdLixos = 45;
        this.qtdLixeiras = 8;
        this.qtdAgentes = 10;
        this.dimenssao = 30;
        criarAmbiente();
    }//GEN-LAST:event_selGrandeActionPerformed

    private void selIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selIniciarActionPerformed
        if(selIniciar.isSelected()){
            btnProximoAgente.setEnabled(true);
            btnProximoCiclo.setEnabled(true);
            selPequeno.setEnabled(false);
            selMedio.setEnabled(false);
            selGrande.setEnabled(false);
            if(!ambienteIniciado){
                iniciarAmbiente();
                ambienteIniciado = true;
            }
        }else{
            inicializaBotoes();
        }
    }//GEN-LAST:event_selIniciarActionPerformed

    private void btnProximoCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoCicloActionPerformed
        simulador.iniciarCiclo();
    }//GEN-LAST:event_btnProximoCicloActionPerformed

    private void btnProximoAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoAgenteActionPerformed
        simulador.iniciarProximoAgente();
    }//GEN-LAST:event_btnProximoAgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barra;
    private javax.swing.JButton btnProximoAgente;
    private javax.swing.JButton btnProximoCiclo;
    private javax.swing.JTextPane campoInformacoes;
    private javax.swing.ButtonGroup gupoTamanho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPanel painelAmbiente;
    private javax.swing.JPanel painelBarra;
    private javax.swing.JPanel painelFilhoAmbiente;
    private javax.swing.JPanel painelInformacoes;
    private javax.swing.JPanel painelPai;
    private javax.swing.JPanel painelScrollAmbiente;
    private javax.swing.JScrollPane scrollAmbiente;
    private javax.swing.JToggleButton selGrande;
    private javax.swing.JToggleButton selIniciar;
    private javax.swing.JToggleButton selMedio;
    private javax.swing.JToggleButton selPequeno;
    // End of variables declaration//GEN-END:variables

    private void inicializaBotoes(){
        btnProximoAgente.setEnabled(false);
        btnProximoCiclo.setEnabled(false);
        selPequeno.setEnabled(true);
        selMedio.setEnabled(true);
        selGrande.setEnabled(true);
    }
    private void iniciarAmbiente(){
        simulador.iniciarAmbiente();
    }
    
    private void criarAmbiente(){
        Dimension d = new Dimension(dimenssao*40, dimenssao*40);
        painelAmbiente.removeAll();
        
        painelAmbiente.setLayout(new java.awt.GridLayout(dimenssao, dimenssao));
        
        painelAmbiente.setPreferredSize(d);
        painelAmbiente.setMinimumSize(d);
        painelAmbiente.setMaximumSize(d);
        
        painelScrollAmbiente.setPreferredSize(d);
        
        this.simulador = new Simulador(this,dimenssao,qtdLixos,qtdLixeiras,qtdAgentes);
        criarQuadrantes();
        atualizaCiclo(simulador.getAmbiente());
    }
    
    private void criarQuadrantes(){
        this.quadrantes = new JLabel[dimenssao][dimenssao];
        for(int l=0;l<dimenssao;l++){
            for(int c=0;c<dimenssao;c++){
                JLabel jl = new JLabel();
                Border eb = new LineBorder(Color.BLACK);
                jl.setBorder(eb);
                jl.setHorizontalAlignment(JLabel.CENTER);
                
                jl.setText(" ");
                
                quadrantes[l][c] = jl;
                painelAmbiente.add(quadrantes[l][c]);
            }
        }
    }
    
    @Override
    public void atualizaCiclo(Ambiente ambiente){
        int d = ambiente.getDimenssao();
        for(int l=0;l<d;l++){
            for(int c=0;c<d;c++){
                Quadrante qd = ambiente.getQuadrante(l, c);
                if(qd.estaVazio())quadrantes[l][c].setText("");
                else quadrantes[l][c].setText(qd.getPeca().getNome());
            }
        }
        
        String style="<style type=\"text/css\">" +
                "  table{" +
                "     border-bottom: 1px #CCCCCC solid;" +
                "     border-right: 1px #CCCCCC solid;" +
                "     margin-bottom: 5px;"+
                "  }" +
                "  th, td{" +
                "	  border-left:1px #CCCCCC solid;" +
                "	  border-top:1px #CCCCCC solid;" +
                "  }" +
                "  td {" +
                "	text-align: center;" +
                "}" +
                "</style>";
        String informacoes="<html>" +
                "<head>"+style+"</head><body>";
        informacoes+="<h3 style=\"text-align:center;\">Agentes</h3>"
                + "<div>";
        for(Agente ag:simulador.getAgentes()){
            informacoes+="<table border=\"0\" cellpadding=\"2\" align=\"center\" cellspacing=\"0\">" +
                    "<tr>" +
                    "<th rowspan=\"2\" scope=\"col\">"+ag.getNome()+"</th>" +
                    "<th colspan=\"2\" scope=\"col\"><h4>Saco Lixo Seco</h4></th>" +
                    "<th colspan=\"2\" scope=\"col\"><h4>Saco Lixo Orgânico</h4></th>" +
                    "</tr>"+
                    "<tr>" +
                    "<td>"+ag.getQtdLixoSeco()+"</td>" +
                    "<td>"+ag.getMaxLixo()+"</td>" +
                    "<td>"+ag.getQtdLixoOrganico()+"</td>" +
                    "<td>"+ag.getMaxLixo()+"</td>" +
                    "</tr>"+
                    "</table>";
        }
        informacoes+="</div>";
        informacoes+="<h3 style=\"text-align:center;\">Lixeiras</h3>"
                + "<div>";
        for(Lixeira lx:simulador.getLixeiras()){
            informacoes+="<table border=\"0\" cellpadding=\"2\" align=\"center\" cellspacing=\"0\">" +
                    "<tr>" +
                    "<th rowspan=\"2\" scope=\"col\">"+lx.getNome()+"</th>" +
                    "<th scope=\"col\"><h4>Ocupado</h4></th>" +
                    "<th scope=\"col\"><h4>Capacidade</h4></th>" +
                    "</tr>"+
                    "<tr>" +
                    "<td>"+lx.getQtdLixos()+"</td>" +
                    "<td>"+lx.getCapacidade()+"</td>" +
                    "</tr>"+
                    "</table>";
        }
        informacoes+="</div>";
        informacoes+="</body></html>";
        campoInformacoes.setText(informacoes);
    }

}
